[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["models/**"]

[[redirects]]
  from = "/home"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/tmdb/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/movie/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/recommend/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200
